# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy the source code
COPY tsconfig.json ./
COPY src ./src

# Build the project
RUN npm run build

# Expose port if needed (not really used for stdio, but optional)
EXPOSE 8080

# Run the MCP server
CMD [ "node", "build/index.js" ]
